baseURL = 'https://snarr.github.io/Engine/'
languageCode = 'en-us'
title = 'Engine'
description = 'A 2D game engine library in JavaScript based on the Canvas API'
theme = 'engine-docs'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Examples"
    url = "/examples/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3