name = "Engine Docs"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "A custom theme for displaying information and examples about Engine"
homepage = "https://snarr.github.io/Engine/"
min_version = "0.41.0"

[author]
  name = "Jacob Snarr"
  homepage = "https://www.sn4rr.com/"